---
title: "Assignment_8_notebook"
output: html_document
---
##install programs
instal.packages(tidyverse)
instal.packages(gapminder)
instal.packages(dplyr)

```{r}
library(tidyverse)
library(gapminder)
library(dplyr)
library(knitr)
```

```{r}
##visualize full gapminder dataset in environments
data(gapminder)
View(gapminder)
```

```{r}
##summary of gapminder dataset
summary(gapminder)
```

```{r}
##use attach function to not have to type name of dataframe for each function
attach(gapminder)
median(pop)
hist(lifeExp)
```

```{r}
##histogram of the populations (log-transformed)
hist(log(pop))
```

```{r}
##boxplot of life expectancy per continent
boxplot(lifeExp ~ continent)
```

```{r}
##scatterplot of y=life expectancy and x=log(gdp-per-capita)
plot(lifeExp ~ log(gdpPercap))
```

```{r}
##T-test of life expectancy between South Africa and Ireland from filtered data set "df1"
df1 <- gapminder%>%
  select(country, lifeExp)%>%
  filter(country == "South Africa" |
           country == "Ireland")
t.test(data = df1, lifeExp ~ country)
```

```{r}
##load ggplot2
library(ggplot2)
```

```{r}
##Color enhanced single-plot of life expectancy bs log-transformed gdp-per-capita, colored by continent, dot-size by population, with smooth function
gapminder%>%
  filter(gdpPercap < 50000)%>%
  ggplot(aes(x=log(gdpPercap), y=lifeExp, col=continent, size=pop))+
  geom_point(alpha=0.3)+
  geom_smooth(method = lm)
```

```{r}
##Faceted scatterplot, colored by year, faceted by continent, with smooth function
gapminder%>%
  filter(gdpPercap < 50000)%>%
  ggplot(aes(x=log(gdpPercap), y=lifeExp, col=year, size=pop))+
  geom_point(alpha=0.3)+
  geom_smooth(method = lm)+
  facet_wrap(~continent)
```

```{r}
##summary display of linear model test of life expectancy by gdp-per-capita and population
summary(lm(lifeExp ~ gdpPercap+pop))
```